apiVersion: v1
kind: Secret
metadata:
  name: tenant-access-control-plane-secrets
type: Opaque
stringData:
  database-url: postgres://postgres:postgres@postgres:5432/tenant_access_control_plane
  redis-url: redis://redis:6379
  session-secret: replace-this
