apiVersion: v1
kind: Service
metadata:
  name: tenant-access-control-plane
spec:
  selector:
    app: tenant-access-control-plane
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
